services:
  django_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "C:/Users/yohan/OneDrive/Bureau/M2MIAGE/PROJET_FONCTIONNE/comparator/django_server:/app"
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "postgres://user:password@db_server:5432/db_name"
    depends_on:
      - db_server

  db_server:
    image: postgres:13
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  django_server:
